services:

    vida-de-avion-dashboard-web:

        container_name: vida-de-avion-dashboard-web

        image: softwareshinobi/vida-de-avion-dashboard-web

        build: 

            context: web

            dockerfile: Dockerfile

        ports:

            - 8080:80

    vida-de-avion-dashboard-docs:

        container_name: vida-de-avion-dashboard-docs

        image: softwareshinobi/vida-de-avion-dashboard-docs

        build: 

            context: docs

            dockerfile: Dockerfile

        ports:

            - 8881:80

    vida-de-avion-dashboard-api:

        container_name: vida-de-avion-dashboard-api
        
        image: softwareshinobi/vida-de-avion-dashboard-api

        depends_on:

           - vida-de-avion-dashboard-database

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: unless-stopped

        ports:

            - "8888:8888"

        environment:

            DB_HOST: vida-de-avion-dashboard-database

            DB_NAME: vida_de_avion

            DB_USER: vida_de_avion

            DB_PASS: vida_de_avion

    vida-de-avion-dashboard-database:

        container_name: vida-de-avion-dashboard-database

        image: mariadb

        ##   volumes:

        ##       - ./.container-volumes/mariadb-server:/var/lib/mysql

        ports:

            - "8886:3306"

        environment:

            MYSQL_ROOT_PASSWORD: aggiepride

            MYSQL_DATABASE: vida_de_avion

            MYSQL_USER: vida_de_avion

            MYSQL_PASSWORD: vida_de_avion

    vida-de-avion-dashboard-phpmyadmin:

        container_name: vida-de-avion-dashboard-phpmyadmin

        image: beeyev/phpmyadmin-lightweight

        depends_on:

           - vida-de-avion-dashboard-database

        links:

           - vida-de-avion-dashboard-database

        ports:

            - 8885:80

        environment:

            PMA_HOST: vida-de-avion-dashboard-database

            PMA_PORT: 3306

            PMA_ARBITRARY: 1
